blueprint:
  name: Z2M - EnOcean PTM215Z (Friends of Hue) switch, single button, multiple clicks
  description: ''
  domain: automation
  input:
    controller:
      name: (Zigbee2MQTT) Controller Name
      description: The name of the controller as defined in z2m (e.g. Livingroom Switch)
      default: ""
    base_topic:
      name: (Zigbee2MQTT) Base mqtt topic
      description: The base topic as configured in z2m
      default: zigbee2mqtt
    target:
      name: HA device name, action entity
      description: The entity from HA
      selector:
        entity:
          domain: light
          multiple: true 
    dim_speed:
      name: Dimming Speed
      description: The speed of the dimming effect. 
      default: 50
      selector:
        number:
          min: 1
          max: 500
          step: 1
    button:
      name: Button to configure
      selector:
        number:
          min: 1
          max: 4
          mode: box
    hold_delay:
      name: Hold delay
      description:
        If the button has been held more than the configured Hold delay, the corresponding held action is triggered.
      default: 500
      selector:
        number:
          min: 100.0
          max: 1000.0
          unit_of_measurement: milliseconds
          mode: box
          step: 10.0

mode: single
max_exceeded: silent

variables:
  hold_delay: !input "hold_delay"
  button: !input "button"
trigger_variables:
  base_topic: !input "base_topic"
  controller: !input "controller"
trigger:
  - platform: mqtt
    topic: "{{ base_topic ~ '/' ~ controller }}"
condition:
  - condition: template
    value_template: >
      {{
        trigger.payload_json.action == "press_" ~ button
      }}
actions:
  - wait_for_trigger:
      - platform: mqtt
        topic: "{{ base_topic ~ '/' ~ controller ~ '/action' }}"
        payload: "{{ 'release_' ~ button }}"
    timeout:
       milliseconds: !input "hold_delay"
  - if:
    - "{{ wait.completed }}"
  - then: 
    - action: light.turn_off
      target: 
        entity_id: !input target
  - else:
    - action: light.turn_on
      target:
        entity_id: !input target
  