blueprint:
  name: Z2M - EnOcean PTM215Z (Friends of Hue) switch, single button, multiple clicks
  description: ''
  domain: automation
  input:
    controller:
      name: (Zigbee2MQTT) Controller Name
      description: The name of the controller as defined in z2m (e.g. Livingroom Switch)
      default: ""
    base_topic:
      name: (Zigbee2MQTT) Base mqtt topic
      description: The base topic as configured in z2m
      default: zigbee2mqtt
    target:
      name: HA device name, action entity
      description: The entity from HA
      selector:
        entity:
          domain: light
          multiple: true 
    dim_speed:
      name: Dimming Speed
      description: The speed of the dimming effect. 
      default: 50
      selector:
        number:
          min: 1
          max: 500
          step: 1
    button:
      name: Button to configure
      selector:
        number:
          min: 1
          max: 4
          mode: box
    hold_delay:
      name: Hold delay
      description:
        If the button has been held more than the configured Hold delay, the corresponding held action is triggered.
      default: 500
      selector:
        number:
          min: 100.0
          max: 1000.0
          unit_of_measurement: milliseconds
          mode: box
          step: 10.0
  source_url: https://raw.githubusercontent.com/mmalkus/HA_EnOcean_215Z/refs/heads/main/1_button.yml
  
mode: single
max_exceeded: silent

variables:
  hold_delay: !input "hold_delay"
  button: !input "button"
  nr_clicks: 0

trigger_variables:
  base_topic: !input "base_topic"
  controller: !input "controller"
trigger:
  - platform: mqtt
    topic: "{{ base_topic ~ '/' ~ controller }}"
condition:
  - condition: template
    value_template: >
      {{
        trigger.payload_json.action == "press_" ~ button
      }}
actions:
  - repeat:
      until: "{{ wait.completed or nr_clicks == 4}}"
      sequence: 
        - wait_for_trigger:
            - platform: mqtt
              topic: "{{ base_topic ~ '/' ~ controller ~ '/action' }}"
              payload: "{{ 'release_' ~ button }}"
          timeout:
            milliseconds: !input "hold_delay"
        - wait_for_trigger:
            - platform: mqtt
              topic: "{{ base_topic ~ '/' ~ controller ~ '/action' }}"
              payload: "{{ 'press_' ~ button }}"
          timeout:
            milliseconds: !input "hold_delay"
        - variables:
            nr_clicks: "{{ nr_clicks + 1 }}"
        - action: mqtt.publish
          data:
            topic: '{{ base_topic ~ ''/'' ~ controller ~ ''/test1''}}'
            payload: "{{ nr_clicks }}"
         
  - action: mqtt.publish
    data:
      topic: '{{ base_topic ~ ''/'' ~ controller ~ ''/test''}}'
      payload: "{{ nr_clicks }}"
